### ISSUE TITLE
Image resize function

### ISSUE THREAD

**Issue by PavKmiec** [PavKmiec/Image-Keywording#1]
Clarifai API has a 20mb file upload limit.
Also for performance reasons the image resizing method would be useful.

Implement a function that will resize a copy of the image before it is sent for processing to the  Clarifai API.
Once keywords are generated, save them back to the original image and delete the resized image.

**Comment by kairavkkp** [comment]
@PavKmiec can I take up the issue?

**Comment by PavKmiec** [comment]
@kairavkkp 
Sure, you are welcome to give it a go.

**Comment by saiharsha-22** [comment]
@kairavkkp I have also tried to resize image function like @kairavkkp. I took reference from StackOverflow and python articles to solve the issue, so it took some time to solve it and I am a beginner to open source.  Can you please check my pull request once?
Image resize #3

**Comment by PavKmiec** [comment]
@kairavkkp your solution works well and solves this issue. I will close the issue since it is solved. @saiharsha-22  I will have a look at your solution later on and will leave you a comment on your pull request. thank you both for contributing.
